// <auto-generated />
using System;
using Equipos3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Equipos3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Equipos3.Modelos.Equipo", b =>
                {
                    b.Property<int>("CodigoEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoEvento"));

                    b.Property<string>("CTE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rdf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subestacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoEvento");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            CodigoEvento = 3,
                            CTE = "CTE Oriente",
                            Elemento = "BL Guajira 230 Soacha 2",
                            Fecha = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEquipo = "BL Guajirá 230 KV Sogamoso 1 SEL321",
                            Opciones = "Activo",
                            PL1 = "Sí",
                            PL2 = "No",
                            Propietario = "Emtelco",
                            Rdf = "Activo",
                            SOE = "Sí",
                            Subestacion = "Guajira 230 KV",
                            TipoDeEquipo = "Relé de presentación"
                        },
                        new
                        {
                            CodigoEvento = 2,
                            CTE = "CTE Occidente",
                            Elemento = "BL Amazonas 230 rio 2",
                            Fecha = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEquipo = "BL Amazonas 230 KV rio 1 SEL321",
                            Opciones = "Activo",
                            PL1 = "Sí",
                            PL2 = "Sí",
                            Propietario = "5 Five",
                            Rdf = "Activo",
                            SOE = "NO",
                            Subestacion = "Amazonas 230 KV",
                            TipoDeEquipo = "Relé de presentación"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
